### ISSUE TITLE
facing issue with unresolved dependency skuber_2.11/0.7-SNAPSHOT

### ISSUE THREAD

**Issue by darjisanket** [adenda/maestro#2]
I am trying compile and build project but facing below issue in resolving dependency:
May someone please help me to resolve dependancy 

[info] Resolving io.doriordan#skuber_2.11;0.7-SNAPSHOT ...
[warn] 	module not found: io.doriordan#skuber_2.11;0.7-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/local/.ivy2/local/io.doriordan/skuber_2.11/0.7-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/doriordan/skuber_2.11/0.7-SNAPSHOT/skuber_2.11-0.7-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/local/.sbt/preloaded/io.doriordan/skuber_2.11/0.7-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/local/.sbt/preloaded/io/doriordan/skuber_2.11/0.7-SNAPSHOT/skuber_2.11-0.7-SNAPSHOT.pom
[warn] ==== Sonatype Releases: tried
[warn]   https://oss.sonatype.org/service/repositories/releases/io/doriordan/skuber_2.11/0.7-SNAPSHOT/skuber_2.11-0.7-SNAPSHOT.pom
[warn] ==== bintray-skuber: tried
[warn]   http://dl.bintray.com/oriordan/skuber/io.doriordan/skuber_2.11/0.7-SNAPSHOT/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.doriordan#skuber_2.11;0.7-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.doriordan:skuber_2.11:0.7-SNAPSHOT (/Users/local/Redsky/redis-demo/maestro/build.sbt#L28-39)
[warn] 		  +- com.adendamedia:maestro_2.11:0.7.3
sbt.ResolveException: unresolved dependency: io.doriordan#skuber_2.11;0.7-SNAPSHOT: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: io.doriordan#skuber_2.11;0.7-SNAPSHOT: not found

**Comment by sjking** [comment]
The problem seems to be related to the dependency https://github.com/doriordan/skuber. During development a locally built snapshot of the skuber library was built because of an issue with the use of Kubernetes StatefulSet API endpoints by the skuber library. See the issue here: https://github.com/doriordan/skuber/pull/47. This issue was closed, and has been apparently resolved in an upgraded skuber library version. It is possible the public API of the upgraded skuber library has changed. To get the project to compile will likely require updating this dependency and making any necessary changes in the maestro code to make use of the upgraded API.
